config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  
  # Books routes
  get '/books', to: 'books#index', as: 'books'
  get '/books/new', to: 'books#new', as: 'new_book'
  post '/books', to: 'books#create'
  get '/books/:id/edit', to: 'books#edit', as: 'edit_book'
  patch '/books/:id', to: 'books#update'
  delete '/books/:id', to: 'books#destroy', as: 'book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
# app/models/book.rb
class Book < ApplicationRecord
    validates :title, presence: true
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
      # Placeholder for displaying all books (since we don't have a database)
      @books = []
    end
  
    def new
      # Placeholder for the new book form
    end
  
    def create
      # Placeholder for creating a new book
      redirect_to root_path, notice: "Book was successfully created."
    end
  
    def edit
      # Placeholder for editing a book
    end
  
    def update
      # Placeholder for updating a book
      redirect_to root_path, notice: "Book was successfully updated."
    end
  
    def destroy
      # Placeholder for deleting a book
      redirect_to root_path, notice: "Book was successfully deleted."
    end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @books = Book.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/books/index.html.erb
<!-- app/views/books/index.html.erb -->
<h1>All Books</h1>
<!-- Add more content if needed -->

app/views/books/new.html.erb
<h1>Add a New Book</h1>

<%= form_with url: books_path, method: :post do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :published_year %>
    <%= form.text_field :published_year %>
  </div>

  <div>
    <%= form.submit "Create Book", class: "btn btn-primary" %>
  </div>
<% end %>

<%= link_to "Back to Home", root_path, class: "btn btn-secondary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookCollection</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/books/_form.html.erb
<!-- app/views/books/_form.html.erb -->
<%= form_with(model: @book, local: true) do |form| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, 'error') %> prohibited this book from being saved:</h2>

      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/layouts/books/destroy.html.erb
<!-- app/views/books/destroy.html.erb -->
<h1>Delete <%= @book.title %></h1>
<p>Are you sure you want to delete this book?</p>
<%= link_to 'Yes, Delete', @book, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Back to Home', books_path %>

app/views/layouts/books/edit.html.erb
<!-- app/views/books/edit.html.erb -->
<h1>Edit <%= @book.title %></h1>
<%= render 'form' %>
<%= link_to 'Back to Home', books_path %>

app/views/layouts/books/index.html.erb
<h1>All Books</h1>
<% @books.each do |book| %>
  <p><%= link_to book.title, book_path(book) %></p>
<% end %>
<%= link_to 'Add a Book', new_book_path %>

app/views/layouts/books/new.html.erb
<!-- app/views/books/new.html.erb -->
<h1>Add a Book</h1>
<%= render 'form' %>
<%= link_to 'Back to Home', books_path %>

app/views/layouts/books/show.html.erb
<!-- app/views/books/show.html.erb -->
<h1><%= @book.title %></h1>
<p><strong>Author:</strong> <%= @book.author %></p>
<p><strong>Price:</strong> <%= @book.price %></p>
<p><strong>Published Date:</strong> <%= @book.published_date %></p>
<%= link_to 'Back to Home', books_path %>

app/views/pages/home.html.erb
<h1>Welcome to Book Application!</h1>

<h2>CRUD Functions</h2>
<%= link_to "View All Books", books_path, class: "btn btn-primary" %>
<%= link_to "Add a New Book", new_book_path, class: "btn btn-success" %>
<%= link_to "Edit a Book", edit_book_path(1), class: "btn btn-warning" %>
<%= link_to "Delete a Book", book_path(1), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>